# Cyclist Bike-Share Case Study - Data Cleaning Process

**Objective:** Prepare the four 2019 quarterly Cyclist trip files for comparing ride behaviour between casual riders and annual members.

## Workflow

1. Load and inspect the quarterly files.
2. Standardize column names and combine the data.
3. Keep the columns needed for the business question.
4. Standardize data types and customer labels.
5. Create `ride_length` and `day_of_week` from the timestamps.
6. Review invalid durations, inspect unusually long rides, and run final checks.
7. Export the cleaned dataset for the analysis notebook.

> **Before running:** The four `read_csv` lines below point to a folder on the original Windows computer. Keep the source CSV files at those paths, or update the paths for your own computer before running the notebook from top to bottom. The source files are not included in this notebook.

## 1. Load libraries and quarterly data

Import pandas and NumPy, then load the four quarterly source files.

In [1]:
import numpy as np
import pandas as pd

In [2]:
q1 = pd.read_csv("..//data//raw//Divvy_Trips_2019_Q1.csv")
q2 = pd.read_csv("..//data//raw//Divvy_Trips_2019_Q2.csv")
q3 = pd.read_csv("..//data//raw//Divvy_Trips_2019_Q3.csv")
q4 = pd.read_csv("..//data//raw//Divvy_Trips_2019_Q4.csv")

## 2. Inspect the quarterly datasets

Check each quarterly file's columns, shape, missing values, and duplicate rows before combining them.

### Inspection reference

- `dtypes`: data type of each column.
- `shape`: number of rows and columns.
- `isnull().sum()`: missing-value count for each column.
- `duplicated().sum()`: number of duplicate rows.

In [3]:
q1.dtypes

trip_id                int64
start_time               str
end_time                 str
bikeid                 int64
tripduration             str
from_station_id        int64
from_station_name        str
to_station_id          int64
to_station_name          str
usertype                 str
gender                   str
birthyear            float64
dtype: object

In [4]:
q1.shape

(365069, 12)

In [5]:
q1.isnull().sum()

trip_id                  0
start_time               0
end_time                 0
bikeid                   0
tripduration             0
from_station_id          0
from_station_name        0
to_station_id            0
to_station_name          0
usertype                 0
gender               19711
birthyear            18023
dtype: int64

In [6]:
q1.duplicated().sum()

np.int64(0)

In [7]:
q2.dtypes

01 - Rental Details Rental ID                         int64
01 - Rental Details Local Start Time                    str
01 - Rental Details Local End Time                      str
01 - Rental Details Bike ID                           int64
01 - Rental Details Duration In Seconds Uncapped        str
03 - Rental Start Station ID                          int64
03 - Rental Start Station Name                          str
02 - Rental End Station ID                            int64
02 - Rental End Station Name                            str
User Type                                               str
Member Gender                                           str
05 - Member Details Member Birthday Year            float64
dtype: object

In [8]:
q2.shape

(1108163, 12)

In [9]:
q2.isnull().sum()

01 - Rental Details Rental ID                            0
01 - Rental Details Local Start Time                     0
01 - Rental Details Local End Time                       0
01 - Rental Details Bike ID                              0
01 - Rental Details Duration In Seconds Uncapped         0
03 - Rental Start Station ID                             0
03 - Rental Start Station Name                           0
02 - Rental End Station ID                               0
02 - Rental End Station Name                             0
User Type                                                0
Member Gender                                       185554
05 - Member Details Member Birthday Year            180953
dtype: int64

In [10]:
q2.duplicated().sum()

np.int64(0)

In [11]:
q3.dtypes

trip_id                int64
start_time               str
end_time                 str
bikeid                 int64
tripduration             str
from_station_id        int64
from_station_name        str
to_station_id          int64
to_station_name          str
usertype                 str
gender                   str
birthyear            float64
dtype: object

In [12]:
q3.shape

(1640718, 12)

In [13]:
q3.isnull().sum()

trip_id                   0
start_time                0
end_time                  0
bikeid                    0
tripduration              0
from_station_id           0
from_station_name         0
to_station_id             0
to_station_name           0
usertype                  0
gender               287350
birthyear            278094
dtype: int64

In [14]:
q3.duplicated().sum()

np.int64(0)

In [15]:
q4.dtypes

trip_id                int64
start_time               str
end_time                 str
bikeid                 int64
tripduration             str
from_station_id        int64
from_station_name        str
to_station_id          int64
to_station_name          str
usertype                 str
gender                   str
birthyear            float64
dtype: object

In [16]:
q4.shape

(704054, 12)

In [17]:
q4.isnull().sum()

trip_id                  0
start_time               0
end_time                 0
bikeid                   0
tripduration             0
from_station_id          0
from_station_name        0
to_station_id            0
to_station_name          0
usertype                 0
gender               66591
birthyear            61681
dtype: int64

In [18]:
q4.duplicated().sum()

np.int64(0)

### Initial inspection findings

The quarterly files use inconsistent column names, so the Q2 headings are standardized in the next section. The initial duplicate checks found no duplicate rows. Missing values appeared in `gender` and `birthyear`; these fields are not needed for the current business question. Each quarterly dataset contains 12 columns.

## 3. Standardize column names

Align the Q2 column names with the convention used in the other quarterly files, then check that all four schemas match.

In [19]:
q1.columns

Index(['trip_id', 'start_time', 'end_time', 'bikeid', 'tripduration',
       'from_station_id', 'from_station_name', 'to_station_id',
       'to_station_name', 'usertype', 'gender', 'birthyear'],
      dtype='str')

In [20]:
q2.columns

Index(['01 - Rental Details Rental ID', '01 - Rental Details Local Start Time',
       '01 - Rental Details Local End Time', '01 - Rental Details Bike ID',
       '01 - Rental Details Duration In Seconds Uncapped',
       '03 - Rental Start Station ID', '03 - Rental Start Station Name',
       '02 - Rental End Station ID', '02 - Rental End Station Name',
       'User Type', 'Member Gender',
       '05 - Member Details Member Birthday Year'],
      dtype='str')

In [21]:
q2.columns = [
    'trip_id',
    'start_time',
    'end_time',
    'bikeid',
    'tripduration',
    'from_station_id',
    'from_station_name',
    'to_station_id',
    'to_station_name',
    'usertype',
    'gender',
    'birthyear'
]

In [22]:
q2.columns

Index(['trip_id', 'start_time', 'end_time', 'bikeid', 'tripduration',
       'from_station_id', 'from_station_name', 'to_station_id',
       'to_station_name', 'usertype', 'gender', 'birthyear'],
      dtype='str')

In [23]:
# check if all of our column names are same
list(q1.columns) == list(q2.columns) == list(q3.columns) == list(q4.columns)

True

## 4. Combine the quarterly datasets

Concatenate the four quarterly DataFrames into one table, then reset the index so row labels run continuously.

In [24]:
# merge the four datasets
data = pd.concat([q1, q2, q3, q4], axis=0)

In [25]:
data.info() # see there are indices not aligned

<class 'pandas.DataFrame'>
Index: 3818004 entries, 0 to 704053
Data columns (total 12 columns):
 #   Column             Dtype
---  ------             -----
 0   trip_id            int64
 1   start_time         str
 2   end_time           str
 3   bikeid             int64
 4   tripduration       str
 5   from_station_id    int64
 6   from_station_name  str
 7   to_station_id      int64
 8   to_station_name    str
 9   usertype           str
 10  gender             str
 11  birthyear          float64
dtypes: float64(1), int64(4), str(7)
memory usage: 378.7 MB

In [26]:
data = data.reset_index(drop=True) # reset indices
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 3818004 entries, 0 to 3818003
Data columns (total 12 columns):
 #   Column             Dtype
---  ------             -----
 0   trip_id            int64
 1   start_time         str
 2   end_time           str
 3   bikeid             int64
 4   tripduration       str
 5   from_station_id    int64
 6   from_station_name  str
 7   to_station_id      int64
 8   to_station_name    str
 9   usertype           str
 10  gender             str
 11  birthyear          float64
dtypes: float64(1), int64(4), str(7)
memory usage: 349.5 MB

## 5. Select columns for the analysis

The business question is about differences between casual riders and annual members. The `gender` and `birthyear` columns are not needed for this comparison, so they are removed from the working dataset. Their missing values do not require dropping otherwise usable trips.

In [27]:
data = data.drop(['gender','birthyear'], axis=1)
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 3818004 entries, 0 to 3818003
Data columns (total 10 columns):
 #   Column             Dtype
---  ------             -----
 0   trip_id            int64
 1   start_time         str
 2   end_time           str
 3   bikeid             int64
 4   tripduration       str
 5   from_station_id    int64
 6   from_station_name  str
 7   to_station_id      int64
 8   to_station_name    str
 9   usertype           str
dtypes: int64(4), str(6)
memory usage: 291.3 MB

## 6. Standardize data types

Convert the timestamps to datetime values and prepare the supplied `tripduration` field as a numeric duration in seconds.

### Convert timestamps

Parse `start_time` and `end_time` as datetime values.

In [28]:
# convert start_time and end_time from 'str' to 'datetime' datatype
data['start_time'] = pd.to_datetime(data['start_time'])
data['end_time'] = pd.to_datetime(data['end_time'])
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 3818004 entries, 0 to 3818003
Data columns (total 10 columns):
 #   Column             Dtype
---  ------             -----
 0   trip_id            int64
 1   start_time         datetime64[us]
 2   end_time           datetime64[us]
 3   bikeid             int64
 4   tripduration       str
 5   from_station_id    int64
 6   from_station_name  str
 7   to_station_id      int64
 8   to_station_name    str
 9   usertype           str
dtypes: datetime64[us](2), int64(4), str(4)
memory usage: 291.3 MB

### Inspect the combined data

Review sample records and the supplied duration values before converting `tripduration` to a numeric type.

In [29]:
data.head()

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype
0,21742443,2019-01-01 00:04:37,2019-01-01 00:11:07,2167,390.0,199,Wabash Ave & Grand Ave,84,Milwaukee Ave & Grand Ave,Subscriber
1,21742444,2019-01-01 00:08:13,2019-01-01 00:15:34,4386,441.0,44,State St & Randolph St,624,Dearborn St & Van Buren St (*),Subscriber
2,21742445,2019-01-01 00:13:23,2019-01-01 00:27:12,1524,829.0,15,Racine Ave & 18th St,644,Western Ave & Fillmore St (*),Subscriber
3,21742446,2019-01-01 00:13:45,2019-01-01 00:43:28,252,"1,783.0",123,California Ave & Milwaukee Ave,176,Clark St & Elm St,Subscriber
4,21742447,2019-01-01 00:14:52,2019-01-01 00:20:56,1170,364.0,173,Mies van der Rohe Way & Chicago Ave,35,Streeter Dr & Grand Ave,Subscriber

In [30]:
data['tripduration'].head()

0      390.0
1      441.0
2      829.0
3    1,783.0
4      364.0
Name: tripduration, dtype: str

In [31]:
pd.to_numeric(data['tripduration'], errors='coerce').head()

0    390.0
1    441.0
2    829.0
3      NaN
4    364.0
Name: tripduration, dtype: float64

### Prepare `tripduration` for numeric conversion

The duration values contain commas as thousands separators. Remove those commas before converting the column to numeric values.

In [32]:
data['tripduration'].head()

0      390.0
1      441.0
2      829.0
3    1,783.0
4      364.0
Name: tripduration, dtype: str

In [33]:
data['tripduration'].str # this let's us access string methods and apply to column which contains strings

In [34]:
# this will remove all the commas in our tripduration column
data['tripduration'].str.replace(",","").head()

0     390.0
1     441.0
2     829.0
3    1783.0
4     364.0
Name: tripduration, dtype: str

In [35]:
data['tripduration'] = pd.to_numeric(data['tripduration'].str.replace(',',''), errors='raise')

In [36]:
data['tripduration'].head()

0     390.0
1     441.0
2     829.0
3    1783.0
4     364.0
Name: tripduration, dtype: float64

In [37]:
data['tripduration'].info()

<class 'pandas.Series'>
RangeIndex: 3818004 entries, 0 to 3818003
Series name: tripduration
Non-Null Count    Dtype
--------------    -----
3818004 non-null  float64
dtypes: float64(1)
memory usage: 29.1 MB

In [38]:
data['tripduration'].dtype

dtype('float64')

In [39]:
data['tripduration'].isnull().sum()

np.int64(0)

### Diagnostic check: duration calculated from timestamps

Temporarily calculate elapsed seconds from `start_time` and `end_time` to inspect the records. This first derived column is removed after the check; the final `ride_length` field is created later alongside `day_of_week`.

In [40]:
# now let's calculate our ride_length, the calculated time from start_time and end_time in seconds

data['ride_length'] = (data['end_time']-data['start_time']).dt.total_seconds() # we write .dt to access time methods

In [41]:
data['ride_length'].info()

<class 'pandas.Series'>
RangeIndex: 3818004 entries, 0 to 3818003
Series name: ride_length
Non-Null Count    Dtype
--------------    -----
3818004 non-null  float64
dtypes: float64(1)
memory usage: 29.1 MB

In [42]:
data['ride_length'].describe()

count    3.818004e+06
mean     1.450451e+03
std      2.985226e+04
min     -3.382000e+03
25%      4.110000e+02
50%      7.090000e+02
75%      1.284000e+03
max      1.063202e+07
Name: ride_length, dtype: float64

In [43]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 3818004 entries, 0 to 3818003
Data columns (total 11 columns):
 #   Column             Dtype
---  ------             -----
 0   trip_id            int64
 1   start_time         datetime64[us]
 2   end_time           datetime64[us]
 3   bikeid             int64
 4   tripduration       float64
 5   from_station_id    int64
 6   from_station_name  str
 7   to_station_id      int64
 8   to_station_name    str
 9   usertype           str
 10  ride_length        float64
dtypes: datetime64[us](2), float64(2), int64(4), str(3)
memory usage: 320.4 MB

In [44]:
data = data.drop('ride_length', axis=1)

In [45]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 3818004 entries, 0 to 3818003
Data columns (total 10 columns):
 #   Column             Dtype
---  ------             -----
 0   trip_id            int64
 1   start_time         datetime64[us]
 2   end_time           datetime64[us]
 3   bikeid             int64
 4   tripduration       float64
 5   from_station_id    int64
 6   from_station_name  str
 7   to_station_id      int64
 8   to_station_name    str
 9   usertype           str
dtypes: datetime64[us](2), float64(1), int64(4), str(3)
memory usage: 291.3 MB

## 7. Standardize customer types

Inspect the `usertype` column, check for missing labels, and standardize the two categories to `Member` and `Casual` for the analysis.

In [46]:
data['usertype'].info()

<class 'pandas.Series'>
RangeIndex: 3818004 entries, 0 to 3818003
Series name: usertype
Non-Null Count    Dtype
--------------    -----
3818004 non-null  str
dtypes: str(1)
memory usage: 29.1 MB

In [47]:
data['usertype'].isnull().sum()

np.int64(0)

In [48]:
data['usertype'].value_counts()

usertype
Subscriber    2937367
Customer       880637
Name: count, dtype: int64

In [49]:
# standardize the name as used in our case study 
data['usertype'] = data['usertype'].replace({
    'Subscriber' : 'Member',
    'Customer' : 'Casual'
})
data['usertype'].value_counts()

usertype
Member    2937367
Casual     880637
Name: count, dtype: int64

## 8. Validate the supplied duration

Review the distribution of the original `tripduration` field and count non-positive values. Keep this separate from the timestamp-derived `ride_length` check so the two duration measures are not confused.

In [50]:
# validate tripduration
print(data["tripduration"].describe())

count    3.818004e+06
mean     1.450203e+03
std      2.985414e+04
min      6.100000e+01
25%      4.110000e+02
50%      7.090000e+02
75%      1.283000e+03
max      1.062840e+07
Name: tripduration, dtype: float64

In [51]:
# any negative values in tripduration
print((data['tripduration'] <= 0).sum())

0

In [52]:
# convert tripduration to whole number
data['tripduration'] = data['tripduration'].astype(int)

In [53]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 3818004 entries, 0 to 3818003
Data columns (total 10 columns):
 #   Column             Dtype
---  ------             -----
 0   trip_id            int64
 1   start_time         datetime64[us]
 2   end_time           datetime64[us]
 3   bikeid             int64
 4   tripduration       int64
 5   from_station_id    int64
 6   from_station_name  str
 7   to_station_id      int64
 8   to_station_name    str
 9   usertype           str
dtypes: datetime64[us](2), int64(5), str(3)
memory usage: 291.3 MB

## 9. Create the analysis columns

Create two fields from the timestamps:

- `ride_length`: elapsed time from `start_time` to `end_time`, stored in seconds.
- `day_of_week`: the weekday on which the ride started, derived from `start_time`.

These will be used in the member-versus-casual analysis. The original `tripduration` column is retained so its values can be compared with the calculated duration.

In [54]:
# let's get back to cleaning

In [55]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 3818004 entries, 0 to 3818003
Data columns (total 10 columns):
 #   Column             Dtype
---  ------             -----
 0   trip_id            int64
 1   start_time         datetime64[us]
 2   end_time           datetime64[us]
 3   bikeid             int64
 4   tripduration       int64
 5   from_station_id    int64
 6   from_station_name  str
 7   to_station_id      int64
 8   to_station_name    str
 9   usertype           str
dtypes: datetime64[us](2), int64(5), str(3)
memory usage: 291.3 MB

In [56]:
data['ride_length'] = data['end_time']-data['start_time']
data['ride_length'].info()

<class 'pandas.Series'>
RangeIndex: 3818004 entries, 0 to 3818003
Series name: ride_length
Non-Null Count    Dtype
--------------    -----
3818004 non-null  timedelta64[us]
dtypes: timedelta64[us](1)
memory usage: 29.1 MB

In [57]:
data['ride_length'] = data['ride_length'].dt.total_seconds()

In [58]:
data['ride_length'].info()

<class 'pandas.Series'>
RangeIndex: 3818004 entries, 0 to 3818003
Series name: ride_length
Non-Null Count    Dtype
--------------    -----
3818004 non-null  float64
dtypes: float64(1)
memory usage: 29.1 MB

In [59]:
data['ride_length'].head()

0     390.0
1     441.0
2     829.0
3    1783.0
4     364.0
Name: ride_length, dtype: float64

In [60]:
data['ride_length'] = data['ride_length'].astype(int)

In [61]:
data['ride_length'].head()

0     390
1     441
2     829
3    1783
4     364
Name: ride_length, dtype: int64

In [62]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 3818004 entries, 0 to 3818003
Data columns (total 11 columns):
 #   Column             Dtype
---  ------             -----
 0   trip_id            int64
 1   start_time         datetime64[us]
 2   end_time           datetime64[us]
 3   bikeid             int64
 4   tripduration       int64
 5   from_station_id    int64
 6   from_station_name  str
 7   to_station_id      int64
 8   to_station_name    str
 9   usertype           str
 10  ride_length        int64
dtypes: datetime64[us](2), int64(6), str(3)
memory usage: 320.4 MB

In [63]:
# now calculate week of the day column
data['day_of_week'] = data['start_time'].dt.dayofweek # 1 for monday, 6 for sunday

**Weekday numbering note:** pandas `.dt.dayofweek` uses `0 = Monday` through `6 = Sunday`. Use this mapping when interpreting `day_of_week`; weekday labels can be added later for presentation.

In [64]:
data['day_of_week'].sample(5)

2680694    2
163753     1
17132      4
802621     3
418177     6
Name: day_of_week, dtype: int32

In [65]:
data['day_of_week'].describe()

count    3.818004e+06
mean     2.845892e+00
std      1.933632e+00
min      0.000000e+00
25%      1.000000e+00
50%      3.000000e+00
75%      4.000000e+00
max      6.000000e+00
Name: day_of_week, dtype: float64

### Check non-positive calculated durations

Count records with `ride_length` at or below zero. These records cannot represent a positive elapsed ride duration, so the next cell keeps only rows with `ride_length > 0`.

In [66]:
data[data['ride_length'] <= 0].count()['trip_id'] # negative or zero distance rides

np.int64(13)

In [67]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 3818004 entries, 0 to 3818003
Data columns (total 12 columns):
 #   Column             Dtype
---  ------             -----
 0   trip_id            int64
 1   start_time         datetime64[us]
 2   end_time           datetime64[us]
 3   bikeid             int64
 4   tripduration       int64
 5   from_station_id    int64
 6   from_station_name  str
 7   to_station_id      int64
 8   to_station_name    str
 9   usertype           str
 10  ride_length        int64
 11  day_of_week        int32
dtypes: datetime64[us](2), int32(1), int64(6), str(3)
memory usage: 335.0 MB

In [68]:
data = data[data['ride_length'] > 0] # 13 rows removed.

In [69]:
data.info()

<class 'pandas.DataFrame'>
Index: 3817991 entries, 0 to 3818003
Data columns (total 12 columns):
 #   Column             Dtype
---  ------             -----
 0   trip_id            int64
 1   start_time         datetime64[us]
 2   end_time           datetime64[us]
 3   bikeid             int64
 4   tripduration       int64
 5   from_station_id    int64
 6   from_station_name  str
 7   to_station_id      int64
 8   to_station_name    str
 9   usertype           str
 10  ride_length        int64
 11  day_of_week        int32
dtypes: datetime64[us](2), int32(1), int64(6), str(3)
memory usage: 364.1 MB

## 10. Review unusually long durations

Inspect rides longer than 24 hours using the supplied `tripduration` field, then compare the supplied duration with calculated `ride_length` for the 50 longest calculated rides. This is a review step, not an automatic outlier-removal rule: very long values are kept unless there is evidence they are invalid.

In [70]:
# Number of rides lasting more than 24 hours
long_rides = data[data["tripduration"] > 86400]

print("Rides over 24 hours:", len(long_rides))

print(
    "Percentage of all rides:",
    round(len(long_rides) / len(data) * 100, 3),
    "%"
)

# Inspect the 10 longest rides
display(
    long_rides.sort_values(
        "tripduration",
        ascending=False
    )[
        [
            "trip_id",
            "start_time",
            "end_time",
            "tripduration",
            "usertype"
        ]
    ].head(10)
)

Rides over 24 hours: 1848
Percentage of all rides: 0.048 %

,trip_id,start_time,end_time,tripduration,usertype
148897,21920842,2019-02-14 14:44:13,2019-06-17 16:04:35,10628400,Casual
1753537,23798837,2019-07-16 18:17:58,2019-10-29 14:01:52,9056633,Member
3189137,25302386,2019-10-06 13:57:02,2020-01-13 21:55:24,8585902,Casual
1839638,23889502,2019-07-22 12:09:36,2019-10-25 10:56:54,8203637,Member
3367117,25487192,2019-10-19 15:14:50,2020-01-21 13:54:35,8120385,Casual
1669835,23710210,2019-07-12 13:08:10,2019-10-12 10:32:18,7939448,Casual
2047113,24107150,2019-08-01 18:45:47,2019-10-29 12:36:57,7667469,Casual
1630590,23661214,2019-07-10 10:25:13,2019-10-06 11:26:25,7606871,Casual
1618591,23648641,2019-07-09 17:28:05,2019-10-04 18:55:47,7522062,Casual
1756534,23801970,2019-07-16 20:44:13,2019-10-10 18:01:25,7420632,Casual

### Compare the two duration fields for the longest calculated rides

The difference below is `tripduration - ride_length`, in seconds. Small differences can arise from how the source fields were recorded; a difference by itself is not enough to label a trip faulty. Review the timestamps and source context before making any exclusion decision.

In [71]:
temp = data.sort_values('ride_length', ascending=False).head(50)[['trip_id','ride_length','tripduration']]
temp.head()

          trip_id  ride_length  tripduration
148897   21920842     10632022      10628400
1753537  23798837      9056634       9056633
3189137  25302386      8582302       8585902
1839638  23889502      8203638       8203637
3367117  25487192      8116785       8120385

In [72]:
temp['tripduration']-temp['ride_length']

148897    -3622
1753537      -1
3189137    3600
1839638      -1
3367117    3600
1669835       0
2047113      -1
1630590      -1
1618591       0
1756534       0
2128692       0
1682846      -1
1789268       0
2046503       0
2259521      -1
1630375       0
2242856       0
3162381    3599
2281327      -1
246297        2
3381219    3599
1904167      -1
2309466       0
1884311       0
1904487      -1
88324     -3598
2422508      -1
2520399       0
2251800      -1
2010454      -1
2466724       0
1727705       0
2547444      -1
2328156       0
2528887      -1
3402785    3600
2175568      -1
2465701      -1
2168154       0
128296    -3598
1792979      -1
3371457    3600
384179        2
2323451      -1
1917792       0
1894097       0
2698032      -1
1677267      -1
2474958       0
2511285       0
dtype: int64

## 11. Final data-quality checks

After creating the analysis columns and removing non-positive calculated durations, check the final working dataset for missing values, duplicate rows, and duplicate trip IDs.

In [73]:
data.info()

<class 'pandas.DataFrame'>
Index: 3817991 entries, 0 to 3818003
Data columns (total 12 columns):
 #   Column             Dtype
---  ------             -----
 0   trip_id            int64
 1   start_time         datetime64[us]
 2   end_time           datetime64[us]
 3   bikeid             int64
 4   tripduration       int64
 5   from_station_id    int64
 6   from_station_name  str
 7   to_station_id      int64
 8   to_station_name    str
 9   usertype           str
 10  ride_length        int64
 11  day_of_week        int32
dtypes: datetime64[us](2), int32(1), int64(6), str(3)
memory usage: 364.1 MB

In [74]:
data.isnull().sum()

trip_id              0
start_time           0
end_time             0
bikeid               0
tripduration         0
from_station_id      0
from_station_name    0
to_station_id        0
to_station_name      0
usertype             0
ride_length          0
day_of_week          0
dtype: int64

In [75]:
data.duplicated().sum()

np.int64(0)

In [76]:
data['trip_id'].duplicated().sum()

np.int64(0)

## 12. Save the cleaned dataset

Export the final `data` DataFrame as `bike_share_cleaned.csv` in the notebook's current working directory. The originally commented export line is retained unchanged below; the final cell performs the export when the notebook is run.

In [77]:
# data.to_csv('bike_share_cleaned.csv', index=False)

In [ ]:
data.to_csv('..//data//processed//bike_share_cleaned.csv', index=False)

---

## Cleaning summary

- Combined the four quarterly 2019 files after standardizing their column names.
- Kept the fields needed for the current member-versus-casual question and removed `gender` and `birthyear` from the working dataset.
- Standardized timestamp types, converted `tripduration` to an integer number of seconds, and standardized customer labels to `Casual` and `Member`.
- Created `ride_length` from the timestamps and `day_of_week` from `start_time`.
- Excluded records with non-positive calculated ride durations.
- Reviewed unusually long rides and compared the supplied and calculated duration fields without automatically deleting long rides.
- Ran final checks for missing values and duplicates before exporting the working dataset.

**Next step:** use `bike_share_cleaned.csv` in the analysis notebook to compare ride counts, ride length, and riding patterns by customer type.